(()=>{
const A='assets/svg/';
const S={eagle:A+'eagle.svg',coco:A+'coco.svg',jersey:A+'jersey.svg',ball:A+'ball.svg',coffee:A+'coffee.svg',trophy:A+'trophy.svg',whistle:A+'whistle.svg',wild:A+'wild.svg',bonus:A+'bonus.svg'};
const keys=Object.keys(S),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}};
const st=Object.assign({coins:256780,bet:2500,totalWin:5750,free:8,freeTotal:10,mult:3,level:24,levelPct:67,collection:42,room:0,auto:false,spinning:false,sound:true,haptics:true,jackpots:{minor:25000,major:125000,grand:500000}},store.get('seaEagleSpinsV3',{}));
st.jackpots=Object.assign({minor:25000,major:125000,grand:500000},st.jackpots||{});
const d={coins:st.coins,win:st.totalWin,bet:st.bet,minor:st.jackpots.minor,major:st.jackpots.major,grand:st.jackpots.grand};let autoT=null,audio=null,hold=null;
function fmt(n){return Math.round(n).toLocaleString('en-AU')}function save(){store.set('seaEagleSpinsV3',st)}
function tween(n,f,t,dur=280){if(!n)return;if(f===t){n.textContent=fmt(t);return}cancelAnimationFrame(n._r||0);let s=performance.now();let step=x=>{let p=Math.min(1,(x-s)/dur),e=1-Math.pow(1-p,3);n.textContent=fmt(f+(t-f)*e);if(p<1)n._r=requestAnimationFrame(step);else n.textContent=fmt(t)};n._r=requestAnimationFrame(step)}
function beep(f=440,d=.05,type='square',v=.03){if(!st.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.value=v;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.stop(audio.currentTime+d+.02)}catch(e){}}
function buzz(p=18){try{if(st.haptics&&navigator.vibrate)navigator.vibrate(p)}catch(e){}}
function toast(a,b=''){let t=q('#toast');t.innerHTML=a+(b?'<small>'+b+'</small>':'');t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1600)}
function render(anim=true){let c=Math.round(st.coins),b=Math.round(st.bet),w=Math.round(st.totalWin);anim?tween(q('#coins'),d.coins,c):q('#coins').textContent=fmt(c);q('#pageCoins').textContent=fmt(c);d.coins=c;anim?tween(q('#bet'),d.bet,b,220):q('#bet').textContent=fmt(b);d.bet=b;anim?tween(q('#win'),d.win,w,260):q('#win').textContent=fmt(w);d.win=w;q('#free').textContent=st.free+' / '+st.freeTotal;q('#mult').textContent='x'+st.mult;['minor','major','grand'].forEach(k=>{let n=Math.round(st.jackpots[k]);anim?tween(q('#'+k),d[k],n,420):q('#'+k).textContent=fmt(n);d[k]=n});q('#levelNo').textContent=st.level;q('#levelPct').textContent=Math.round(st.levelPct)+'%';q('#levelFill').style.width=Math.max(0,Math.min(100,st.levelPct))+'%';save()}
function rand(){let r=Math.random();if(r<.065)return'bonus';if(r<.155)return'wild';return keys[Math.floor(Math.random()*(keys.length-2))]}function img(s){return '<img draggable="false" alt="'+s+'" src="'+S[s]+'">'}
function initGrid(){q('#reels').innerHTML='';for(let i=0;i<15;i++)q('#reels').insertAdjacentHTML('beforeend','<div class="cell">'+img(rand())+'</div>')}
function setGrid(a,w=[]){qa('.cell').forEach((c,i)=>{c.className='cell'+(w.includes(i)?' win':'');c.innerHTML=img(a[i])})}
function calc(a){let win=0,ws=[];for(let r=0;r<3;r++){let idx=[0,1,2,3,4].map(c=>r*5+c),v=idx.map(i=>a[i]),first=v.find(x=>x!=='wild')||v[0],cnt=0;for(let x of v){if(x===first||x==='wild')cnt++;else break}if(cnt>=3&&first!=='bonus'){let base={eagle:14,coco:10,jersey:7,ball:6,coffee:5,trophy:12,whistle:4,wild:18}[first]||4;win+=Math.round(st.bet*(cnt-2)*base*st.mult/2);ws.push(...idx.slice(0,cnt))}}let bonus=a.filter(x=>x==='bonus').length;if(bonus>=3){st.free+=8;st.freeTotal=Math.max(st.freeTotal,st.free+2);st.mult=Math.min(6,st.mult+1);win+=st.bet*bonus*st.mult;ws.push(...a.map((x,i)=>x==='bonus'?i:-1).filter(i=>i>=0));toast('SHEBBA BONUS','8 free spins + multiplier');beep(880,.12,'triangle',.06)}return{win,winners:[...new Set(ws)]}}
function result(){let a=Array.from({length:15},rand);if(Math.random()<.52){let row=Math.floor(Math.random()*3),s=['eagle','coco','jersey','ball','trophy'][Math.floor(Math.random()*5)],len=3+Math.floor(Math.random()*3);for(let c=0;c<len;c++)a[row*5+c]=(c===1&&Math.random()<.22)?'wild':s}if(Math.random()<.18)[2,7,12].forEach(i=>a[i]='bonus');return a}
function spin(turbo=false){if(st.spinning)return;if(st.coins<st.bet&&st.free<=0){toast('NOT ENOUGH COINS','Tap + for fake coins');q('#app').classList.add('shake');setTimeout(()=>q('#app').classList.remove('shake'),280);return}st.spinning=true;if(st.free>0)st.free--;else st.coins-=st.bet;st.totalWin=0;render();q('#reels').classList.add('spinning');beep(190,.08,'sawtooth');buzz(20);let ticks=turbo?7:14;let tick=()=>{qa('.cell').forEach(c=>c.innerHTML=img(rand()));if(--ticks>0)setTimeout(tick,turbo?42:72);else finish()};tick()}
function finish(){let a=result(),r=calc(a);q('#reels').classList.remove('spinning');setGrid(a,r.winners);st.levelPct+=Math.max(3,Math.min(14,Math.round((r.win||st.bet)/2300)));while(st.levelPct>=100){st.levelPct-=100;st.level++;st.coins+=7000;toast('LEVEL UP','Now level '+st.level)}if(r.win>0){st.totalWin=r.win;st.coins+=r.win;st.collection=Math.min(120,st.collection+Math.ceil(r.win/st.bet));showWin(r.win,r.winners.length>5?'MEGA WIN':'LINE WIN');rain(r.win>st.bet*10?34:16);beep(540,.1,'triangle',.06);buzz([30,45,30])}else st.mult=Math.max(1,st.mult-1);st.spinning=false;render()}
function showWin(n,l){q('#winBig').textContent=(l==='MEGA WIN'?'MEGA WIN ':'WIN ')+'+'+fmt(n);q('#winLabel').textContent=l==='MEGA WIN'?'SEA EAGLE PAYOUT':'LINE PAYOUT';q('#winPopup').classList.add('show');clearTimeout(q('#winPopup')._t);q('#winPopup')._t=setTimeout(()=>q('#winPopup').classList.remove('show'),1650)}
function rain(n){let box=q('#rain');box.innerHTML='';for(let i=0;i<n;i++){let c=document.createElement('i');c.className='coinDrop';c.style.left=Math.random()*96+'%';c.style.animationDelay=Math.random()*.35+'s';box.appendChild(c)}setTimeout(()=>box.innerHTML='',1900)}
function topup(n=25000,label='25,000 FAKE COINS'){st.coins+=n;toast(label,'No money charged');rain(12);render()}
function modal(h){q('#modalCard').innerHTML=h;q('#modal').classList.add('show')}function close(){q('#modal').classList.remove('show')}function payouts(){modal('<h2>PAYOUTS</h2><p>Match 3 or more from the left. WILD substitutes. BONUS gives free spins. Coins are for this family app only.</p><button data-modal="close">CLOSE</button>')}function menu(){modal('<h2>PAUSED</h2><p>Sea Eagle Spins is a private family app with fake coins only.</p><button data-modal="close">RESUME</button>')}
function tile(sym,title,copy,act='play'){return '<button class="tile" data-action="'+act+'">'+img(sym)+'<b>'+title+'</b><span>'+copy+'</span></button>'}
function page(p){if(p==='game')return showGame();q('#game').classList.remove('active');q('#page').classList.add('active');let h='';if(p==='home')h='<h1>WELCOME BACK</h1><p>Dad’s private Sea Eagle pokies-style app. Fake coins only.</p><button class="bigBtn" data-action="play">PLAY NOW</button><div class="list">'+tile('bonus','DAILY BONUS','Claim +10,000 fake coins','daily')+tile('trophy','MISSIONS','Complete challenges and level up','missions')+tile('eagle','LIVE JACKPOTS','Minor, Major and Grand climb live','play')+'</div>';if(p==='games')h='<h1>CHOOSE GAME</h1><div class="list">'+tile('eagle','CLASSIC SPINS','Five reels, polished base game')+tile('trophy','MEGA SPINS','Bigger multipliers and faster hits')+tile('bonus','BONUS HUNT','More bonus chances')+tile('wild','FREE SPIN FRENZY','Stack free spins')+tile('ball','JACKPOT RUSH','Chase the Grand')+'</div>';if(p==='shop')h='<h1>SHOP</h1><p>Fake coin packs only. No real purchases.</p><div class="shop"><button data-action="pack1"><strong>🪙</strong><b>25,000</b><span>$1.99</span></button><button data-action="pack2"><strong>💰</strong><b>75,000</b><span>$4.99</span></button><button data-action="pack3"><strong>🏦</strong><b>200,000</b><span>$9.99</span></button><button data-action="pack4"><strong>🦅</strong><b>550,000</b><span>$19.99</span></button></div>';if(p==='collection')h='<h1>COLLECTION '+st.collection+' / 120</h1><p>Unlock cards as wins land.</p><div class="cards">'+keys.map(k=>img(k)).join('')+'</div>';if(p==='room')h='<h1>CLUB ROOM</h1><p>Use fake coins to build Dad’s Sea Eagle den.</p><div class="roomArt">🛋️☕🏆</div><div class="list">'+tile('coffee','COFFEE BAR','Add Manly Brew upgrades','room')+tile('trophy','TROPHY WALL','Show level rewards','room')+tile('eagle','EAGLE SIGN','Light up the clubhouse','room')+'</div>';if(p==='map')h='<h1>SEASON MAP</h1><p>Progress through match-day levels and unlock room rewards.</p><div class="list">'+tile('ball','BROOKVALE GATES','Level 1–15')+tile('coffee','CLUBHOUSE','Level 16–30')+tile('jersey','DERBY NIGHT','Level 31–45')+tile('trophy','GRAND FINAL','Level 46+')+'</div>';if(p==='settings')h='<h1>SETTINGS</h1><div class="list">'+tile('whistle','SOUND','Toggle audio','sound')+tile('wild','HAPTICS','iPhone vibration where supported','haptics')+tile('bonus','PRIVACY','Local browser save only','privacy')+'</div>';q('#pageContent').innerHTML=h;render(false)}
function showGame(){q('#page').classList.remove('active');q('#game').classList.add('active');render(false)}function auto(){st.auto=!st.auto;toast(st.auto?'AUTO SPIN ON':'AUTO SPIN OFF');if(st.auto){spin(true);autoT=setInterval(()=>{if(!st.spinning)spin(true)},1300)}else{clearInterval(autoT);autoT=null}save()}
document.addEventListener('pointerdown',e=>{if(e.target.closest('.spin'))hold=setTimeout(()=>spin(true),420)});document.addEventListener('pointerup',e=>{clearTimeout(hold);let b=e.target.closest('[data-action],[data-page],[data-modal]');if(!b)return;e.preventDefault();beep(330,.035);if(b.dataset.page)page(b.dataset.page);let a=b.dataset.action;if(a==='spin')spin(false);else if(a==='auto')auto();else if(a==='minus'){st.bet=Math.max(50,st.bet-50);render()}else if(a==='plusBet'){st.bet=Math.min(5000,st.bet+50);render()}else if(a==='topup')topup();else if(a==='play')showGame();else if(a==='menu')menu();else if(a==='payouts')payouts();else if(a==='daily')topup(10000,'DAILY BONUS CLAIMED');else if(a==='missions')modal('<h2>MISSIONS</h2><p>Spin 10 times, hit Wild, find Bonus. Rewards are fake coins.</p><button data-modal="close">DONE</button>');else if(a==='pack1')topup(25000,'25,000 FAKE COINS');else if(a==='pack2')topup(75000,'75,000 FAKE COINS');else if(a==='pack3')topup(200000,'200,000 FAKE COINS');else if(a==='pack4')topup(550000,'550,000 FAKE COINS');else if(a==='room'){st.room++;st.coins=Math.max(0,st.coins-5000);toast('ROOM UPGRADED','Clubhouse improved');render()}else if(a==='sound'){st.sound=!st.sound;toast('SOUND '+(st.sound?'ON':'OFF'));save()}else if(a==='haptics'){st.haptics=!st.haptics;toast('HAPTICS '+(st.haptics?'ON':'OFF'));save()}else if(a==='privacy')modal('<h2>PRIVACY</h2><p>Local browser save only. Fake coins only.</p><button data-modal="close">CLOSE</button>');if(b.dataset.modal)close()},{passive:false});
q('#modal').addEventListener('pointerup',e=>{if(e.target.id==='modal')close()});setInterval(()=>{st.jackpots.minor+=100+Math.random()*160;st.jackpots.major+=340+Math.random()*420;st.jackpots.grand+=800+Math.random()*980;render(true)},2200);initGrid();render(false);
})();