(()=>{
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)], pick=a=>a[Math.floor(Math.random()*a.length)];
const EM={eagle:'🦅',coco:'🐶',jersey:'👕',ball:'🏉',coffee:'☕',trophy:'🏆',whistle:'📣',wild:'🦅',bonus:'⭐'};
const LAB={eagle:'EAGLE',coco:'COCO',jersey:'11',ball:'BALL',coffee:'BREW',trophy:'CUP',whistle:'CALL',wild:'WILD',bonus:'BONUS'};
const PAY={eagle:16,trophy:14,coco:11,jersey:8,ball:7,coffee:6,whistle:5,wild:20};
const KEYS=Object.keys(EM);
const SAVE='seaEagleSpinsV10';
const old=JSON.parse(localStorage.getItem(SAVE)||'null');
const fresh={coins:75000,bet:500,totalWin:0,free:0,freeTotal:0,mult:1,level:1,xp:0,collection:0,spins:0,wins:0,losses:0,bigWins:0,bestWin:0,challengesWon:0,manlyCorrect:0,zachJobs:0,streak:0,lastDaily:0,auto:false,spinning:false,sound:true,haptics:true,jackpots:{minor:15000,major:75000,grand:250000},seen:{}};
const st=Object.assign(fresh,old||{});st.jackpots=Object.assign(fresh.jackpots,st.jackpots||{});st.seen=Object.assign({},st.seen||{});
const d={coins:st.coins,win:st.totalWin,bet:st.bet,minor:st.jackpots.minor,major:st.jackpots.major,grand:st.jackpots.grand};
let autoT=null,hold=null,lastChallenge=0;
const faces={Jake:'🧑‍🦰',Shebba:'👑',David:'😏',Coco:'🐶',Zach:'🧰'};
const lines={
Jake:['That spin had full Brookie chaos energy.','I fear Coco is the actual machine operator.','Dad is going to call this strategy.','This is either iconic or financially fake.','The drama budget on that spin was huge.','That was giving main character at the leagues club.'],
Shebba:['Craig, do not blame the machine.','One more and then coffee.','That was actually not bad, babe.','If this wins, I am taking credit.','Hot caramel latte energy has entered the chat.','Coco could have pressed spin better, honestly.'],
David:['That payout was suspiciously generous.','I have seen better form from a concrete mixer.','He wins once and suddenly he is a professional.','The Sea Eagles accountant is sweating.','That spin was held together with cable ties.','Dad is going to explain that win for forty minutes.'],
Coco:['woof. spin again.','paw selected: chaos.','i require snack commission.','coco jackpot incoming.','bark bark bonus.','dad owes me chicken.'],
Zach:['I could plaster a straighter payline than that.','Lilah and Stella would have picked better.','That win needs a patch coat and a sand.','Dad, that was not skill, that was luck in hi-vis.','I am loving the confidence, but that was cooked.','Plasterer approved. Smooth finish on that payout.']
};
const challenges=[
{id:'m1',who:'Jake',icon:'🦅',title:'MANLY QUICKIE',copy:'What colours are we backing?',answers:[['Maroon and white',1],['Purple and green',0],['Concrete grey',0]],reward:7000,ok:'Correct. Proper Sea Eagle behaviour.'},
{id:'m2',who:'Shebba',icon:'🏉',title:'BROOKIE VIBES',copy:'Where does Dad want the winning energy to feel like?',answers:[['Brookie under lights',1],['A quiet library',0],['The freezer aisle',0]],reward:8500,ok:'Brookie energy locked in.'},
{id:'m3',who:'David',icon:'🦅',title:'SEA EAGLE CHECK',copy:'Which symbol should feel like the top icon?',answers:[['The eagle',1],['The coffee cup',0],['The minus button',0]],reward:6500,ok:'The eagle has landed. Very dramatic.'},
{id:'m4',who:'Jake',icon:'🏆',title:'MATCH DAY QUESTION',copy:'What should Dad yell after a giant payout?',answers:[['Up the Sea Eagles',1],['Where is my spreadsheet',0],['Coco did my tax',0]],reward:9000,ok:'Crowd goes wild. Dad is unbearable.'},
{id:'m5',who:'Coco',icon:'🐾',title:'COCO PAW PICK',copy:'Coco is choosing the lucky paw.',answers:[['Left paw',1],['Right paw',1],['Snack paw',1]],reward:6000,ok:'Coco picked a winner and expects payment.'},
{id:'coffee',who:'Shebba',icon:'☕',title:'SHEBBA COFFEE RUN',copy:'What is Michelle ordering?',answers:[['Hot caramel latte, extra caramel',1],['Plain black tea',0],['Concrete smoothie',0]],reward:8000,ok:'Coffee secured. Shebba bonus paid.'},
{id:'concrete',who:'David',icon:'🧱',title:"CRAIG'S CONCRETE RUN",copy:'Craig needs a perfect slab. Which one are we pouring?',answers:[['Driveway slab',1],['Fairy floss',0],['Gravy pool',0]],reward:9500,ok:'Craig approves. Solid as.'},
{id:'zach1',who:'Zach',icon:'🧰',title:"ZACH'S PLASTER PATCH",copy:'Zach the plasterer needs a smooth finish. What are we doing?',answers:[['Patch, set, sand',1],['Paint over the hole',0],['Ask Coco to lick it flat',0]],reward:11000,ok:'Smooth finish. Lilah and Stella would be proud.'},
{id:'zach2',who:'Zach',icon:'👧',title:'LILAH & STELLA BONUS',copy:'Zach is doing a loving dad check. What do we choose?',answers:[['Cute win for the girls',1],['Boring no bonus',0],['Hide the snacks from Coco',1]],reward:10500,ok:'Lilah and Stella bonus unlocked. Loving dad moment.'},
{id:'david',who:'David',icon:'😏',title:"DAVID'S ROAST ROUND",copy:'David says that last spin was...',answers:[['Clearly rigged for Dad',1],['A tax deduction',0],['Coco doing accounting',0]],reward:7500,ok:'David accepts the suspicious win.'}
];
function fmt(n){return Math.round(n).toLocaleString('en-AU')}
function save(){localStorage.setItem(SAVE,JSON.stringify(st))}
function sfx(k){try{window.SeaEagleAudio&&window.SeaEagleAudio.sfx(k)}catch(e){}}
function buzz(p=18){try{if(st.haptics&&navigator.vibrate)navigator.vibrate(p)}catch(e){}}
function tween(n,f,t,dur=240){if(!n)return;if(f===t){n.textContent=fmt(t);return}cancelAnimationFrame(n._r||0);const a=performance.now();const step=x=>{const p=Math.min(1,(x-a)/dur),e=1-Math.pow(1-p,3);n.textContent=fmt(f+(t-f)*e);p<1?n._r=requestAnimationFrame(step):n.textContent=fmt(t)};n._r=requestAnimationFrame(step)}
function xpNeed(){return 85+st.level*22}
function addXP(n){st.xp+=n;let up=false;while(st.xp>=xpNeed()){st.xp-=xpNeed();st.level++;st.coins+=5000+st.level*350;up=true}if(up){alertBanner('LEVEL UP','Now level '+st.level);setTimeout(()=>say('Shebba','Level '+st.level+' already. Craig is getting confident.'),420);sfx('win')}}
function render(anim=true){const c=Math.round(st.coins),b=Math.round(st.bet),w=Math.round(st.totalWin);anim?tween(q('#coins'),d.coins,c):q('#coins').textContent=fmt(c);q('#pageCoins').textContent=fmt(c);d.coins=c;anim?tween(q('#bet'),d.bet,b):q('#bet').textContent=fmt(b);d.bet=b;anim?tween(q('#win'),d.win,w):q('#win').textContent=fmt(w);d.win=w;q('#free').textContent=st.free+' / '+st.freeTotal;q('#mult').textContent='x'+st.mult;['minor','major','grand'].forEach(k=>{let n=Math.round(st.jackpots[k]);anim?tween(q('#'+k),d[k],n,420):q('#'+k).textContent=fmt(n);d[k]=n});q('#levelNo').textContent=st.level;q('#levelPct').textContent=Math.round((st.xp/xpNeed())*100)+'%';q('#levelFill').style.width=Math.max(0,Math.min(100,(st.xp/xpNeed())*100))+'%';save()}
function symbolName(s){return LAB[s]||String(s).toUpperCase()}
function sym(s){return '<div class="symbolTile '+s+'"><div class="symbolArt">'+EM[s]+'</div><div class="symbolName">'+symbolName(s)+'</div></div>'}
function rand(){let r=Math.random();if(r<.07)return'bonus';if(r<.16)return'wild';return KEYS[Math.floor(Math.random()*(KEYS.length-2))]}
function initGrid(){const r=q('#reels');r.innerHTML='';for(let i=0;i<15;i++)r.insertAdjacentHTML('beforeend','<div class="cell">'+sym(rand())+'</div>')}
function setGrid(a,w=[]){qa('.cell').forEach((c,i)=>{c.className='cell'+(w.includes(i)?' win':'');c.innerHTML=sym(a[i])})}
function alertBanner(a,b=''){let t=q('#toast');t.innerHTML=a+(b?'<small>'+b+'</small>':'');t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1500)}
function say(who,msg){if(q('#modal')?.classList.contains('show'))return;let box=q('#commentary');box.innerHTML='<div class="talk"><div class="face">'+(faces[who]||'🦅')+'</div><div><b>'+who+'</b><span>'+msg+'</span></div></div>';box.classList.add('show');clearTimeout(box._t);box._t=setTimeout(()=>box.classList.remove('show'),2500)}
function randomSay(type){let who=pick(['Jake','Shebba','David','Coco','Zach']), msg=pick(lines[who]);if(type==='win'){who=pick(['Jake','Shebba','David','Zach']);msg=pick(['Dad is going to dine out on that one.','That payout had actual main character energy.','Craig will be unbearable after this.','That was clean. Almost too clean.','Lilah and Stella would be screaming.'])}if(type==='near'){who=pick(['Jake','David','Zach']);msg=pick(['That near miss was emotionally violent.','The machine is teasing Dad now.','One tile away. I am sick.','I could plaster a better outcome than that.'])}if(type==='bonus'){who=pick(['Coco','Jake','Shebba']);msg=pick(['bonus found. snack bonus also required.','That bonus had drama in it.','Free spins, Craig. Behave.'])}say(who,msg)}
function result(){let a=Array.from({length:15},rand);if(Math.random()<.55){let row=Math.floor(Math.random()*3),s=pick(['eagle','coco','jersey','ball','trophy','coffee','whistle']),len=3+Math.floor(Math.random()*3);for(let c=0;c<len;c++)a[row*5+c]=(c===1&&Math.random()<.24)?'wild':s}if(Math.random()<.17)[2,7,12].forEach(i=>a[i]='bonus');if(st.spins>0&&st.spins%12===0){let row=Math.floor(Math.random()*3);a[row*5]='bonus';a[row*5+1]='bonus';a[row*5+2]='bonus'}return a}
function calc(a){let win=0,ws=[],lines=0;for(let r=0;r<3;r++){let idx=[0,1,2,3,4].map(c=>r*5+c),vals=idx.map(i=>a[i]),first=vals.find(v=>v!=='wild')||vals[0],cnt=0;for(let v of vals){if(v===first||v==='wild')cnt++;else break}if(cnt>=3&&first!=='bonus'){win+=Math.round(st.bet*(cnt-2)*(PAY[first]||5)*st.mult/2);ws.push(...idx.slice(0,cnt));lines++}}let bonus=a.filter(x=>x==='bonus').length;if(bonus>=3){st.free+=8;st.freeTotal+=8;st.mult=Math.min(7,st.mult+1);win+=st.bet*bonus*st.mult;ws.push(...a.map((x,i)=>x==='bonus'?i:-1).filter(i=>i>=0));alertBanner('BONUS ROUND','8 free spins + multiplier');setTimeout(()=>randomSay('bonus'),420);sfx('challenge')}return{win,winners:[...new Set(ws)],lines,bonus}}
function nearMiss(a,res){if(res.win||res.bonus>=3)return;let txt='';if(a.filter(x=>x==='bonus').length===2)txt='BONUS NEAR MISS';else if(Math.random()<.35)txt='SO CLOSE';if(!txt)return;let m=q('.machine');m.classList.add('near');let el=document.createElement('div');el.className='nearMissText';el.textContent=txt;q('#app').appendChild(el);setTimeout(()=>{m.classList.remove('near');el.remove()},1150);randomSay('near')}
function spin(turbo=false){if(st.spinning)return;if(st.coins<st.bet&&st.free<=0){alertBanner('NOT ENOUGH COINS','Tap + for fake coins');return}st.spinning=true;st.spins++;st.totalWin=0;if(st.free>0)st.free--;else st.coins-=st.bet;render();q('#reels').classList.add('spinning');q('.machine').classList.add('hot');sfx('spin');buzz(18);if(st.spins%3===1)randomSay('spin');let ticks=turbo?7:14;let tick=()=>{qa('.cell').forEach(c=>c.innerHTML=sym(rand()));if(--ticks>0)setTimeout(tick,turbo?42:70);else finish()};tick()}
function finish(){let a=result(),r=calc(a);q('#reels').classList.remove('spinning');q('.machine').classList.remove('hot');setGrid(a,r.winners);if(r.win>0){st.wins++;st.streak++;st.totalWin=r.win;st.coins+=r.win;st.bestWin=Math.max(st.bestWin,r.win);st.collection=Math.min(180,st.collection+Math.ceil(r.win/Math.max(1,st.bet)));if(r.win>=st.bet*20)st.bigWins++;showWin(r.win,r.win>=st.bet*20?'MEGA WIN':'LINE WIN');rain(r.win>st.bet*12?34:16);addXP(18+r.lines*8+Math.min(20,Math.round(r.win/st.bet)));sfx('win');buzz([25,40,25]);setTimeout(()=>randomSay('win'),620);if(st.streak>0&&st.streak%3===0)setTimeout(()=>miniBonus(),1150)}else{st.losses++;st.streak=0;st.mult=Math.max(1,st.mult-1);addXP(4);nearMiss(a,r)}st.spinning=false;render();if(st.spins-lastChallenge>=3&&Math.random()<.45)setTimeout(()=>showChallenge(),850)}
function showWin(n,label){q('#winBig').textContent=(label==='MEGA WIN'?'MEGA WIN ':'WIN ')+'+'+fmt(n);q('#winLabel').textContent=label==='MEGA WIN'?'SEA EAGLE PAYOUT':'LINE PAYOUT';q('#winPopup').classList.add('show');clearTimeout(q('#winPopup')._t);q('#winPopup')._t=setTimeout(()=>q('#winPopup').classList.remove('show'),1450)}
function rain(n){let box=q('#rain');box.innerHTML='';for(let i=0;i<n;i++){let c=document.createElement('i');c.className='coinDrop';c.style.left=Math.random()*96+'%';c.style.animationDelay=Math.random()*.25+'s';box.appendChild(c)}setTimeout(()=>box.innerHTML='',1600)}
function topup(n=25000,label='25,000 FAKE COINS'){st.coins+=n;alertBanner(label,'No money charged');rain(12);sfx('coin');render()}
function modal(h){q('#modalCard').innerHTML=h;q('#modal').classList.add('show');q('#commentary').classList.remove('show')}
function close(){q('#modal').classList.remove('show')}
function challengeButtons(ch){return ch.answers.map(a=>'<button data-challenge="'+ch.id+'" data-good="'+a[1]+'">'+a[0]+'</button>').join('')}
function showChallenge(id){lastChallenge=st.spins;let ch=id?challenges.find(x=>x.id===id):pick(challenges);say(ch.who,pick(['Question time. Don’t embarrass us.','Answer this for fake coins.','This one is absolutely skill based.','No pressure, but Coco is watching.']));modal('<div class="challengeCard"><div class="challengeIcon">'+ch.icon+'</div><h2>'+ch.title+'</h2><p>'+ch.copy+'</p><p class="challengeReward">Reward: +'+fmt(ch.reward)+' fake coins</p><div class="challengeBtns">'+challengeButtons(ch)+'</div></div>');sfx('challenge')}
function solveChallenge(id,good){let ch=challenges.find(x=>x.id===id)||challenges[0];close();if(good==='1'){st.coins+=ch.reward;st.challengesWon++;if(id[0]==='m')st.manlyCorrect++;if(id.indexOf('zach')===0)st.zachJobs++;addXP(18);alertBanner('CHALLENGE WON','+'+fmt(ch.reward)+' fake coins');say(ch.who,ch.ok);rain(14);sfx('win')}else{alertBanner('CHALLENGE MISSED','David is judging quietly');say('David','That answer was cooked, but I respect the confidence.');sfx('button')}render()}
function miniBonus(){let reward=st.bet*(2+Math.floor(Math.random()*5));modal('<div class="challengeCard"><div class="challengeIcon">⚡</div><h2>HOT STREAK BONUS</h2><p>Three wins in the run. Jake hits the drama button.</p><p class="challengeReward">Instant +'+fmt(reward)+' fake coins</p><div class="challengeBtns"><button data-action="claimMini" data-reward="'+reward+'">CLAIM BONUS</button></div></div>')}
function payouts(){modal('<h2>PAYOUTS</h2><div class="payTable">'+['eagle','trophy','coco','jersey','coffee','ball','whistle','wild','bonus'].map(k=>'<div class="payRow">'+sym(k)+'<b>'+LAB[k]+'</b><span>'+(k==='wild'?'substitutes':k==='bonus'?'3 = free spins':'3+ left to right')+'</span><strong>'+ (k==='bonus'?'BONUS':'x'+(PAY[k]||8)) +'</strong></div>').join('')+'</div><button data-modal="close">CLOSE</button>')}
function menu(){modal('<h2>PAUSED</h2><p>Sea Eagle Spins is a private family pokies-style game with fake coins only. No cash value, prizes or real purchases.</p><button data-modal="close">RESUME</button>')}
function tile(symName,title,copy,act='play'){return '<button class="tile" data-action="'+act+'">'+sym(symName)+'<b>'+title+'</b><span>'+copy+'</span></button>'}
function miniStat(a,b){return '<div class="miniStat"><b>'+a+'</b><span>'+b+'</span></div>'}
function page(p){if(p==='game')return showGame();q('#game').classList.remove('active');q('#page').classList.add('active');let h='';
if(p==='home')h='<div class="pageHero"><h1>LEVEL '+st.level+'</h1><p>Track Dad’s fake-coin reign. More spins unlock more chaos.</p></div><div class="featureRow">'+miniStat(st.spins,'SPINS')+miniStat(st.wins,'WINS')+miniStat(fmt(st.bestWin),'BEST')+'</div><button class="bigBtn" data-action="play">PLAY NOW</button><div class="list">'+tile('bonus','DAILY BONUS','Claim +10,000 fake coins','daily')+tile('eagle','MANLY TRIVIA','More Sea Eagle questions','challengeManly')+tile('trophy','FAMILY QUESTS','Jake, Shebba, David, Zach and Coco','openChallenges')+'</div>';
if(p==='games')h='<div class="pageHero"><h1>CHOOSE GAME</h1><p>Modes are tracked and styled, with more unlocking as Dad levels up.</p></div><div class="list">'+tile('eagle','CLASSIC SPINS','Balanced base game for steady fake-coin wins')+tile('trophy','MEGA SPINS','More volatile wins and louder popups')+tile('bonus','BONUS HUNT','More bonus rounds and free-spin chances')+tile('wild','FREE SPIN FRENZY','Wild-heavy reels and faster spins')+tile('ball','JACKPOT RUSH','Bigger jackpot teases and near misses')+'</div>';
if(p==='shop')h='<div class="pageHero"><h1>SHOP</h1><p>Fake coin packs only. No real purchases.</p></div><div class="shop"><button data-action="pack1"><strong>🪙</strong><b>25,000</b><span>$1.99</span></button><button data-action="pack2"><strong>💰</strong><b>75,000</b><span>$4.99</span></button><button data-action="pack3"><strong>🏦</strong><b>200,000</b><span>$9.99</span></button><button data-action="pack4"><strong>🦅</strong><b>550,000</b><span>$19.99</span></button></div>';
if(p==='collection')h='<div class="pageHero"><h1>COLLECTION '+st.collection+' / 180</h1><p>Cards unlock from wins, quests and bonus rounds.</p></div><div class="featureRow">'+miniStat(st.bigWins,'BIG WINS')+miniStat(st.manlyCorrect,'MANLY')+miniStat(st.zachJobs,'ZACH JOBS')+'</div><div class="cards">'+KEYS.map(k=>sym(k)).join('')+'</div>';
if(p==='map')h='<div class="pageHero"><h1>JACKPOT MAP</h1><p>Progress through Dad’s fake season.</p></div><div class="mapTrack">'+[['1','BROOKVALE GATES','Level 1–5'],['2','SHEBBA COFFEE STAND','Level 6–12'],['3','ZACH PLASTER PATCH','Level 13–20'],['4','COCO BONUS KENNEL','Level 21–35'],['5','GRAND FINAL CHAOS','Level 36+']].map(n=>'<div class="mapNode" data-step="'+n[0]+'"><b>'+n[1]+'</b><span>'+n[2]+'</span></div>').join('')+'</div>';
if(p==='challenges')h='<div class="pageHero"><h1>CHALLENGES</h1><p>More Manly questions, family roasts and Zach plasterer bonuses.</p></div><div class="list">'+tile('eagle','MANLY QUICKIE','Maroon, white and match-day chaos','challengeManly')+tile('coffee','SHEBBA COFFEE RUN','Pick the correct order','challengeCoffee')+tile('coco','COCO PAW PICK','Choose the lucky paw','challengeCoco')+tile('whistle','CRAIG CONCRETE RUN','Help Dad pour the slab','challengeConcrete')+tile('trophy','ZACH PLASTER PATCH','Smooth finish for Lilah and Stella','challengeZach')+tile('bonus',"DAVID'S ROAST ROUND",'Survive the suspicious commentary','challengeDavid')+'</div>';
if(p==='settings')h='<div class="pageHero"><h1>MORE</h1><p>Sound starts after first tap on iPhone.</p></div><div class="list">'+tile('whistle','SOUND','Toggle music and effects','sound')+tile('wild','HAPTICS','iPhone vibration where supported','haptics')+tile('bonus','RESET GAME','Start Dad from level 1 again','resetGame')+'</div>';
q('#pageContent').innerHTML=h;render(false)}
function showGame(){q('#page').classList.remove('active');q('#game').classList.add('active');render(false)}
function auto(){st.auto=!st.auto;alertBanner(st.auto?'AUTO SPIN ON':'AUTO SPIN OFF');if(st.auto){spin(true);autoT=setInterval(()=>{if(!st.spinning&&!q('#modal').classList.contains('show'))spin(true)},1300)}else clearInterval(autoT);save()}
document.addEventListener('pointerdown',e=>{if(e.target.closest('.spin'))hold=setTimeout(()=>spin(true),420)});
document.addEventListener('pointerup',e=>{clearTimeout(hold);let b=e.target.closest('[data-action],[data-page],[data-modal],[data-challenge]');if(!b)return;e.preventDefault();if(b.dataset.challenge){solveChallenge(b.dataset.challenge,b.dataset.good);return}if(b.dataset.page)page(b.dataset.page);let a=b.dataset.action;if(a==='spin')spin(false);else if(a==='auto')auto();else if(a==='minus'){st.bet=Math.max(100,st.bet-100);render()}else if(a==='plusBet'){st.bet=Math.min(7500,st.bet+100);render()}else if(a==='topup')topup();else if(a==='play')showGame();else if(a==='menu')menu();else if(a==='payouts')payouts();else if(a==='daily'){let now=Date.now();if(now-st.lastDaily<1000*60*60*18)alertBanner('DAILY CLAIMED','Try again later');else{st.lastDaily=now;topup(10000,'DAILY BONUS CLAIMED')}}else if(a==='openChallenges')page('challenges');else if(a==='challengeManly')showChallenge(pick(['m1','m2','m3','m4']));else if(a==='challengeCoffee')showChallenge('coffee');else if(a==='challengeCoco')showChallenge('m5');else if(a==='challengeConcrete')showChallenge('concrete');else if(a==='challengeZach')showChallenge(pick(['zach1','zach2']));else if(a==='challengeDavid')showChallenge('david');else if(a==='claimMini'){topup(Number(b.dataset.reward||0),'HOT STREAK BONUS');close();say('Jake','That was deserved. Extremely dramatic.')}else if(a==='pack1')topup(25000,'25,000 FAKE COINS');else if(a==='pack2')topup(75000,'75,000 FAKE COINS');else if(a==='pack3')topup(200000,'200,000 FAKE COINS');else if(a==='pack4')topup(550000,'550,000 FAKE COINS');else if(a==='sound'){st.sound=!st.sound;alertBanner('SOUND '+(st.sound?'ON':'OFF'));save()}else if(a==='haptics'){st.haptics=!st.haptics;alertBanner('HAPTICS '+(st.haptics?'ON':'OFF'));save()}else if(a==='resetGame'){localStorage.removeItem(SAVE);location.reload()}if(b.dataset.modal)close()},{passive:false});
q('#modal').addEventListener('pointerup',e=>{if(e.target.id==='modal')close()});
setInterval(()=>{st.jackpots.minor+=60+Math.random()*120;st.jackpots.major+=160+Math.random()*260;st.jackpots.grand+=400+Math.random()*650;render(true)},2400);
initGrid();render(false);setTimeout(()=>say('Zach','Fresh game. Level 1. Smooth start, like a good plaster finish.'),700);
})();