(()=>{
const EM={eagle:'🦅',coco:'🐶',jersey:'👕',ball:'🏉',coffee:'☕',trophy:'🏆',whistle:'📣',wild:'🦅',bonus:'⭐'};
const LAB={eagle:'EAGLE',coco:'COCO',jersey:'11',ball:'BALL',coffee:'BREW',trophy:'CUP',whistle:'CALL',wild:'WILD',bonus:'BONUS'};
const keys=Object.keys(EM),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const extra=document.createElement('style');
extra.textContent=`.symCard{width:94%;height:94%;border-radius:16%;display:grid;place-items:center;position:relative;background:radial-gradient(circle at 50% 22%,rgba(255,255,255,.33),transparent 38%),linear-gradient(145deg,#8b0034,#160007 72%);box-shadow:inset 0 0 0 .12vh rgba(255,214,95,.42),0 .22vh .42vh #000;overflow:hidden}.symCard:before{content:"";position:absolute;inset:-30%;background:linear-gradient(115deg,transparent 35%,rgba(255,255,255,.12),transparent 62%);transform:rotate(8deg)}.symIcon{font-size:min(7.4vh,52px);filter:drop-shadow(0 .22vh .25vh #000);z-index:2}.symLabel{position:absolute;left:7%;right:7%;bottom:.42vh;border-radius:.32vh;padding:.18vh 0;background:linear-gradient(90deg,#fff0a6,#ffbd20,#9e5100);color:#5b1500;font:900 min(1.55vh,11px) Impact,Arial;text-align:center;letter-spacing:.06em;z-index:3}.tile .symCard{width:4.8vh;height:4.8vh}.tile .symIcon{font-size:3vh}.tile .symLabel{font-size:.9vh}.cards .symCard{height:10vh;width:100%}.cards .symIcon{font-size:4.7vh}.reels.spinning .symCard{animation:spin .16s linear infinite;filter:blur(.18vh) brightness(1.35)}.cell.win .symCard{animation:pulse .7s ease-in-out 3;filter:drop-shadow(0 0 .8vh #ffd45f)}#toast{top:8%!important;z-index:58!important}.winPopup{top:17%!important;z-index:56!important}#modal{z-index:80!important;align-items:flex-start!important;padding-top:10%!important}.challengeCard{width:100%;max-width:36vh}.challengeIcon{font-size:min(6vh,42px);line-height:1}.challengeBtns{display:grid;gap:.75vh;margin-top:1.2vh}.challengeBtns button{width:100%;min-height:5.4vh}.challengeReward{color:#ffe680;font-size:min(2.2vh,16px)}#commentary{position:absolute;z-index:53;left:5%;right:5%;top:63%;pointer-events:none;opacity:0;transform:translateY(.8vh);transition:.2s}#commentary.show{opacity:1;transform:translateY(0)}.talk{display:grid;grid-template-columns:4.8vh 1fr;gap:.8vh;align-items:center;border:.18vh solid rgba(255,216,96,.9);border-radius:1.5vh;padding:.65vh .85vh;background:linear-gradient(180deg,rgba(95,0,37,.97),rgba(18,0,8,.97));box-shadow:0 .8vh 2.5vh #000}.talk .face{width:4.8vh;height:4.8vh;border-radius:50%;display:grid;place-items:center;background:radial-gradient(circle at 35% 22%,#fff1aa,#ffbd20 43%,#7a2600);font-size:2.7vh}.talk b{display:block;color:#ffe680;font-size:min(1.85vh,13px);line-height:1}.talk span{display:block;margin-top:.2vh;font-family:Arial,sans-serif;font-weight:900;font-size:min(1.55vh,11px);line-height:1.2;color:#fff2ce}.missionPill{display:inline-flex;align-items:center;gap:.5vh;border:.12vh solid #ffd45f;border-radius:999px;padding:.45vh .75vh;margin:.2vh;background:rgba(255,208,60,.12);font-family:Arial,sans-serif;font-weight:900;font-size:min(1.3vh,10px)}.roomArt{display:none!important}`;
document.head.appendChild(extra);
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}};
const st=Object.assign({coins:256780,bet:2500,totalWin:5750,free:8,freeTotal:10,mult:3,level:24,levelPct:67,collection:42,spins:0,streak:0,challengesWon:0,auto:false,spinning:false,sound:true,haptics:true,jackpots:{minor:25000,major:125000,grand:500000}},store.get('seaEagleSpinsV5',{}));
st.jackpots=Object.assign({minor:25000,major:125000,grand:500000},st.jackpots||{});
const d={coins:st.coins,win:st.totalWin,bet:st.bet,minor:st.jackpots.minor,major:st.jackpots.major,grand:st.jackpots.grand};
let autoT=null,audio=null,hold=null,lastChallenge=0;
const voices={Jake:['That spin was giving Brookie under lights.','I fear Coco carried that one.','Dad is absolutely claiming skill here.','That was almost iconic.','I need a replay on that immediately.'],Shebba:['Craig, do not blame the machine.','One more and then coffee.','That was actually not bad, babe.','Coco could have pressed spin better.','Hot caramel latte energy.'],David:['That payout was suspiciously generous.','I have seen better form from the concrete mixer.','Surely that was rigged for Dad.','Classic. He wins and suddenly it is skill.','The Sea Eagles accountant is sweating.'],Coco:['woof. spin again.','paw selected: chaos.','i require snack commission.','coco jackpot incoming.','bark bark bonus.']};
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function fmt(n){return Math.round(n).toLocaleString('en-AU')}
function save(){store.set('seaEagleSpinsV5',st)}
function tween(n,f,t,dur=280){if(!n)return;if(f===t){n.textContent=fmt(t);return}cancelAnimationFrame(n._r||0);let s=performance.now();let step=x=>{let p=Math.min(1,(x-s)/dur),e=1-Math.pow(1-p,3);n.textContent=fmt(f+(t-f)*e);if(p<1)n._r=requestAnimationFrame(step);else n.textContent=fmt(t)};n._r=requestAnimationFrame(step)}
function beep(f=440,d=.05,type='square',v=.03){if(!st.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.value=v;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.stop(audio.currentTime+d+.02)}catch(e){}}
function buzz(p=18){try{if(st.haptics&&navigator.vibrate)navigator.vibrate(p)}catch(e){}}
function toast(a,b=''){let t=q('#toast');t.innerHTML=a+(b?'<small>'+b+'</small>':'');t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1600)}
function say(who,msg){const face={Jake:'🧑‍🦰',Shebba:'👑',David:'😏',Coco:'🐶'}[who]||'🦅',box=q('#commentary');box.innerHTML='<div class="talk"><div class="face">'+face+'</div><div><b>'+who+'</b><span>'+msg+'</span></div></div>';box.classList.add('show');clearTimeout(box._t);box._t=setTimeout(()=>box.classList.remove('show'),2600)}
function randomSay(type='spin'){if(q('#modal').classList.contains('show'))return;let names=['Jake','Shebba','David','Coco'];let who=pick(names);let line=pick(voices[who]);if(type==='win'){who=pick(['Jake','Shebba','David']);line=pick(['That is very much a Dad win.','Sea Eagle payout landed.','Okay, that one actually slapped.','Craig will be unbearable after this.'])}if(type==='bonus'){who='Coco';line='bonus found. snack bonus also required.'}if(type==='challenge'){who=pick(['Jake','Shebba','Coco']);line=pick(['Challenge time, no pressure.','Answer this and pretend it was skill.','Pick the paw wisely.'])}say(who,line)}
function render(anim=true){let c=Math.round(st.coins),b=Math.round(st.bet),w=Math.round(st.totalWin);anim?tween(q('#coins'),d.coins,c):q('#coins').textContent=fmt(c);q('#pageCoins').textContent=fmt(c);d.coins=c;anim?tween(q('#bet'),d.bet,b,220):q('#bet').textContent=fmt(b);d.bet=b;anim?tween(q('#win'),d.win,w,260):q('#win').textContent=fmt(w);d.win=w;q('#free').textContent=st.free+' / '+st.freeTotal;q('#mult').textContent='x'+st.mult;['minor','major','grand'].forEach(k=>{let n=Math.round(st.jackpots[k]);anim?tween(q('#'+k),d[k],n,420):q('#'+k).textContent=fmt(n);d[k]=n});q('#levelNo').textContent=st.level;q('#levelPct').textContent=Math.round(st.levelPct)+'%';q('#levelFill').style.width=Math.max(0,Math.min(100,st.levelPct))+'%';save()}
function rand(){let r=Math.random();if(r<.065)return'bonus';if(r<.155)return'wild';return keys[Math.floor(Math.random()*(keys.length-2))]}
function sym(s){return '<div class="symCard '+s+'"><div class="symIcon">'+EM[s]+'</div><div class="symLabel">'+LAB[s]+'</div></div>'}
function initGrid(){q('#reels').innerHTML='';for(let i=0;i<15;i++)q('#reels').insertAdjacentHTML('beforeend','<div class="cell">'+sym(rand())+'</div>')}
function setGrid(a,w=[]){qa('.cell').forEach((c,i)=>{c.className='cell'+(w.includes(i)?' win':'');c.innerHTML=sym(a[i])})}
function calc(a){let win=0,ws=[];for(let r=0;r<3;r++){let idx=[0,1,2,3,4].map(c=>r*5+c),v=idx.map(i=>a[i]),first=v.find(x=>x!=='wild')||v[0],cnt=0;for(let x of v){if(x===first||x==='wild')cnt++;else break}if(cnt>=3&&first!=='bonus'){let base={eagle:14,coco:10,jersey:7,ball:6,coffee:5,trophy:12,whistle:4,wild:18}[first]||4;win+=Math.round(st.bet*(cnt-2)*base*st.mult/2);ws.push(...idx.slice(0,cnt))}}let bonus=a.filter(x=>x==='bonus').length;if(bonus>=3){st.free+=8;st.freeTotal=Math.max(st.freeTotal,st.free+2);st.mult=Math.min(6,st.mult+1);win+=st.bet*bonus*st.mult;ws.push(...a.map((x,i)=>x==='bonus'?i:-1).filter(i=>i>=0));toast('SHEBBA BONUS','8 free spins + multiplier');randomSay('bonus');beep(880,.12,'triangle',.06)}return{win,winners:[...new Set(ws)]}}
function result(){let a=Array.from({length:15},rand);if(Math.random()<.52){let row=Math.floor(Math.random()*3),s=['eagle','coco','jersey','ball','trophy'][Math.floor(Math.random()*5)],len=3+Math.floor(Math.random()*3);for(let c=0;c<len;c++)a[row*5+c]=(c===1&&Math.random()<.22)?'wild':s}if(Math.random()<.18)[2,7,12].forEach(i=>a[i]='bonus');return a}
function spin(turbo=false){if(st.spinning)return;if(st.coins<st.bet&&st.free<=0){toast('NOT ENOUGH COINS','Tap + for fake coins');q('#app').classList.add('shake');setTimeout(()=>q('#app').classList.remove('shake'),280);return}st.spinning=true;st.spins++;if(st.free>0)st.free--;else st.coins-=st.bet;st.totalWin=0;render();q('#reels').classList.add('spinning');beep(190,.08,'sawtooth');buzz(20);if(st.spins%3===1)randomSay('spin');let ticks=turbo?7:14;let tick=()=>{qa('.cell').forEach(c=>c.innerHTML=sym(rand()));if(--ticks>0)setTimeout(tick,turbo?42:72);else finish()};tick()}
function finish(){let a=result(),r=calc(a);q('#reels').classList.remove('spinning');setGrid(a,r.winners);st.levelPct+=Math.max(3,Math.min(14,Math.round((r.win||st.bet)/2300)));while(st.levelPct>=100){st.levelPct-=100;st.level++;st.coins+=7000;toast('LEVEL UP','Now level '+st.level)}if(r.win>0){st.streak++;st.totalWin=r.win;st.coins+=r.win;st.collection=Math.min(120,st.collection+Math.ceil(r.win/st.bet));showWin(r.win,r.winners.length>5?'MEGA WIN':'LINE WIN');rain(r.win>st.bet*10?34:16);beep(540,.1,'triangle',.06);buzz([30,45,30]);setTimeout(()=>randomSay('win'),650)}else{st.streak=0;st.mult=Math.max(1,st.mult-1);beep(160,.05,'square',.02);if(st.spins%4===0)randomSay('spin')}st.spinning=false;render();if(st.spins-lastChallenge>=4&&Math.random()<.38)setTimeout(()=>showChallenge(),900)}
function showWin(n,l){q('#winBig').textContent=(l==='MEGA WIN'?'MEGA WIN ':'WIN ')+'+'+fmt(n);q('#winLabel').textContent=l==='MEGA WIN'?'SEA EAGLE PAYOUT':'LINE PAYOUT';q('#winPopup').classList.add('show');clearTimeout(q('#winPopup')._t);q('#winPopup')._t=setTimeout(()=>q('#winPopup').classList.remove('show'),1650)}
function rain(n){let box=q('#rain');box.innerHTML='';for(let i=0;i<n;i++){let c=document.createElement('i');c.className='coinDrop';c.style.left=Math.random()*96+'%';c.style.animationDelay=Math.random()*.35+'s';box.appendChild(c)}setTimeout(()=>box.innerHTML='',1900)}
function topup(n=25000,label='25,000 FAKE COINS'){st.coins+=n;toast(label,'No money charged');rain(12);render()}
function modal(h){q('#modalCard').innerHTML=h;q('#modal').classList.add('show');q('#commentary').classList.remove('show')}function close(){q('#modal').classList.remove('show')}
const challenges=[{id:'concrete',icon:'🧱',title:'CRAIG\'S CONCRETE RUN',copy:'Craig needs a perfect slab. Which one are we pouring?',answers:[['Driveway slab',1],['Fairy floss',0],['A swimming pool of gravy',0]],reward:12000,ok:'Craig approves the slab. Solid as.'},{id:'coco',icon:'🐾',title:'COCO PAW PICK',copy:'Coco is choosing the lucky paw. Pick one.',answers:[['Left paw',1],['Right paw',1],['Secret snack paw',1]],reward:9000,ok:'Coco picked a winner.'},{id:'manly',icon:'🦅',title:'MANLY QUICK QUESTION',copy:'What colour combo are we backing?',answers:[['Maroon and white',1],['Blue and yellow',0],['Purple glitter only',0]],reward:15000,ok:'Correct. Sea Eagle energy.'},{id:'coffee',icon:'☕',title:'SHEBBA COFFEE RUN',copy:'What is Michelle ordering?',answers:[['Hot caramel latte, extra caramel',1],['Plain black tea',0],['A concrete smoothie',0]],reward:10000,ok:'Coffee secured. Shebba bonus paid.'},{id:'david',icon:'😏',title:'DAVID\'S ROAST ROUND',copy:'David says this spin was...',answers:[['Clearly rigged for Dad',1],['A tax deduction',0],['Coco doing accounting',0]],reward:11000,ok:'David accepts the suspicious win.'}];
function showChallenge(id){lastChallenge=st.spins;let ch=id?challenges.find(x=>x.id===id):pick(challenges);randomSay('challenge');let btns=ch.answers.map((a,i)=>'<button data-challenge="'+ch.id+'" data-good="'+a[1]+'">'+a[0]+'</button>').join('');modal('<div class="challengeCard"><div class="challengeIcon">'+ch.icon+'</div><h2>'+ch.title+'</h2><p>'+ch.copy+'</p><p class="challengeReward">Reward: +'+fmt(ch.reward)+' fake coins</p><div class="challengeBtns">'+btns+'</div></div>')}
function solveChallenge(id,good){let ch=challenges.find(x=>x.id===id)||challenges[0];if(good==='1'){st.coins+=ch.reward;st.challengesWon++;st.levelPct+=7;toast('CHALLENGE WON','+'+fmt(ch.reward)+' fake coins');say('Jake',ch.ok);rain(14);beep(760,.12,'triangle',.06)}else{toast('CHALLENGE MISSED','David is judging quietly');say('David','That answer was cooked, but I respect the confidence.');beep(150,.07,'square',.025)}close();render()}
function payouts(){modal('<h2>PAYOUTS</h2><p>Match 3 or more from the left. WILD substitutes. BONUS gives free spins. Challenges pop up during play for extra fake coins.</p><button data-modal="close">CLOSE</button>')}
function menu(){modal('<h2>PAUSED</h2><p>Sea Eagle Spins is a private family pokies-style game with fake coins only. No cash value, no real purchases.</p><button data-modal="close">RESUME</button>')}
function tile(symName,title,copy,act='play',extra=''){return '<button class="tile" data-action="'+act+'" '+extra+'>'+sym(symName)+'<b>'+title+'</b><span>'+copy+'</span></button>'}
function page(p){if(p==='game')return showGame();q('#game').classList.remove('active');q('#page').classList.add('active');let h='';if(p==='home')h='<h1>WELCOME BACK</h1><p>Dad’s private Sea Eagle spins app. Fake coins only.</p><button class="bigBtn" data-action="play">PLAY NOW</button><div><span class="missionPill">Spins: '+st.spins+'</span><span class="missionPill">Challenges: '+st.challengesWon+'</span><span class="missionPill">Streak: '+st.streak+'</span></div><div class="list">'+tile('bonus','DAILY BONUS','Claim +10,000 fake coins','daily')+tile('trophy','CHALLENGES','Concrete, Coco paw, Manly trivia','openChallenges')+tile('eagle','LIVE JACKPOTS','Minor, Major and Grand climb live','play')+'</div>';if(p==='games')h='<h1>CHOOSE GAME</h1><div class="list">'+tile('eagle','CLASSIC SPINS','Five reels, base game')+tile('trophy','MEGA SPINS','Bigger multipliers and faster hits')+tile('bonus','BONUS HUNT','More bonus chances')+tile('wild','FREE SPIN FRENZY','Stack free spins')+tile('ball','JACKPOT RUSH','Chase the Grand')+'</div>';if(p==='shop')h='<h1>SHOP</h1><p>Fake coin packs only. No real purchases.</p><div class="shop"><button data-action="pack1"><strong>🪙</strong><b>25,000</b><span>$1.99</span></button><button data-action="pack2"><strong>💰</strong><b>75,000</b><span>$4.99</span></button><button data-action="pack3"><strong>🏦</strong><b>200,000</b><span>$9.99</span></button><button data-action="pack4"><strong>🦅</strong><b>550,000</b><span>$19.99</span></button></div>';if(p==='collection')h='<h1>COLLECTION '+st.collection+' / 120</h1><p>Unlock cards as wins land.</p><div class="cards">'+keys.map(k=>sym(k)).join('')+'</div>';if(p==='map')h='<h1>JACKPOT MAP</h1><p>Climb through match-day levels and trigger harder challenges.</p><div class="list">'+tile('ball','BROOKVALE GATES','Level 1–15')+tile('coffee','COFFEE STAND','Level 16–30')+tile('jersey','DERBY NIGHT','Level 31–45')+tile('trophy','GRAND FINAL','Level 46+')+'</div>';if(p==='challenges')h='<h1>CHALLENGES</h1><p>Quick bonus rounds pop during play. Win extra fake coins.</p><div class="list">'+tile('coffee','SHEBBA COFFEE RUN','Pick the right order','challengeCoffee')+tile('coco','COCO PAW PICK','Choose the lucky paw','challengeCoco')+tile('ball','MANLY TRIVIA','Answer the Sea Eagle question','challengeManly')+tile('whistle','CONCRETE JOB','Help Craig pour the slab','challengeConcrete')+'</div>';if(p==='settings')h='<h1>MORE</h1><div class="list">'+tile('whistle','SOUND','Toggle audio','sound')+tile('wild','HAPTICS','iPhone vibration where supported','haptics')+tile('bonus','PRIVACY','Local browser save only','privacy')+'</div>';q('#pageContent').innerHTML=h;render(false)}
function showGame(){q('#page').classList.remove('active');q('#game').classList.add('active');render(false)}
function auto(){st.auto=!st.auto;toast(st.auto?'AUTO SPIN ON':'AUTO SPIN OFF');if(st.auto){spin(true);autoT=setInterval(()=>{if(!st.spinning)spin(true)},1300)}else{clearInterval(autoT);autoT=null}save()}
document.addEventListener('pointerdown',e=>{if(e.target.closest('.spin'))hold=setTimeout(()=>spin(true),420)});
document.addEventListener('pointerup',e=>{clearTimeout(hold);let b=e.target.closest('[data-action],[data-page],[data-modal],[data-challenge]');if(!b)return;e.preventDefault();beep(330,.035);if(b.dataset.challenge){solveChallenge(b.dataset.challenge,b.dataset.good);return}if(b.dataset.page)page(b.dataset.page);let a=b.dataset.action;if(a==='spin')spin(false);else if(a==='auto')auto();else if(a==='minus'){st.bet=Math.max(50,st.bet-50);render()}else if(a==='plusBet'){st.bet=Math.min(5000,st.bet+50);render()}else if(a==='topup')topup();else if(a==='play')showGame();else if(a==='menu')menu();else if(a==='payouts')payouts();else if(a==='daily')topup(10000,'DAILY BONUS CLAIMED');else if(a==='openChallenges')page('challenges');else if(a==='challengeCoffee')showChallenge('coffee');else if(a==='challengeCoco')showChallenge('coco');else if(a==='challengeManly')showChallenge('manly');else if(a==='challengeConcrete')showChallenge('concrete');else if(a==='pack1')topup(25000,'25,000 FAKE COINS');else if(a==='pack2')topup(75000,'75,000 FAKE COINS');else if(a==='pack3')topup(200000,'200,000 FAKE COINS');else if(a==='pack4')topup(550000,'550,000 FAKE COINS');else if(a==='sound'){st.sound=!st.sound;toast('SOUND '+(st.sound?'ON':'OFF'));save()}else if(a==='haptics'){st.haptics=!st.haptics;toast('HAPTICS '+(st.haptics?'ON':'OFF'));save()}else if(a==='privacy')modal('<h2>PRIVACY</h2><p>Local browser save only. Fake coins only. No gambling value, prizes or cash-out.</p><button data-modal="close">CLOSE</button>');if(b.dataset.modal)close()},{passive:false});
q('#modal').addEventListener('pointerup',e=>{if(e.target.id==='modal')close()});
setInterval(()=>{st.jackpots.minor+=100+Math.random()*160;st.jackpots.major+=340+Math.random()*420;st.jackpots.grand+=800+Math.random()*980;render(true)},2200);
initGrid();render(false);setTimeout(()=>say('Coco','woof. press spin and feed the jackpot.'),800);
})();