(()=>{
let ctx, master, musicGain, sfxGain, started=false, musicTimer=null, step=0, wasMuted=false;
const scale=[130.81,146.83,164.81,196.00,220.00,246.94,261.63,293.66,329.63];
function readSave(){try{return JSON.parse(localStorage.getItem('seaEagleSpinsV11')||'{}')}catch(e){return {}}}
function enabled(){return readSave().sound!==false}
function make(){ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();if(!master){master=ctx.createGain();master.gain.value=enabled()?0.34:0;master.connect(ctx.destination);musicGain=ctx.createGain();musicGain.gain.value=.045;musicGain.connect(master);sfxGain=ctx.createGain();sfxGain.gain.value=.9;sfxGain.connect(master)}return ctx}
function syncMute(){if(!master)return;let on=enabled();if(on!==!wasMuted){wasMuted=!on}try{master.gain.setTargetAtTime(on?0.34:0,ctx.currentTime,.03)}catch(e){master.gain.value=on?0.34:0}}
function tone(f=440,d=.08,type='square',vol=.08,delay=0,out){if(!enabled())return;try{make();syncMute();const now=ctx.currentTime+delay,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,now);g.gain.setValueAtTime(vol,now);g.gain.exponentialRampToValueAtTime(.0001,now+d);o.connect(g);g.connect(out||sfxGain||master);o.start(now);o.stop(now+d+.03)}catch(e){}}
function noise(d=.12,vol=.05){if(!enabled())return;try{make();syncMute();const len=Math.max(1,Math.floor(ctx.sampleRate*d)),buf=ctx.createBuffer(1,len,ctx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const s=ctx.createBufferSource(),g=ctx.createGain();g.gain.value=vol;s.buffer=buf;s.connect(g);g.connect(sfxGain||master);s.start()}catch(e){}}
function music(){if(musicTimer)return;musicTimer=setInterval(()=>{if(!ctx||ctx.state==='suspended'||!enabled())return;syncMute();let bass=scale[step%scale.length]/2,lead=scale[(step*2+3)%scale.length];tone(bass,.09,'triangle',.026,0,musicGain);if(step%2===0)tone(lead,.06,'sine',.018,.03,musicGain);if(step%4===0)noise(.025,.012);step++},350)}
function flash(a,b){let t=document.querySelector('#toast');if(!t)return;t.innerHTML=a+'<small>'+b+'</small>';t.classList.add('show');clearTimeout(t._audioT);t._audioT=setTimeout(()=>t.classList.remove('show'),1150)}
function start(){try{make();ctx.resume&&ctx.resume();syncMute();if(!started){started=true;music();if(enabled())flash('SOUND ON','Music and effects unlocked')}}catch(e){}}
function sfx(kind){start();if(!enabled())return;if(kind==='spin'){tone(180,.07,'sawtooth',.08);tone(240,.06,'sawtooth',.05,.07);noise(.08,.025)}else if(kind==='win'){[520,660,820,1040].forEach((f,i)=>tone(f,.09,'triangle',.075,i*.07));noise(.22,.035)}else if(kind==='button'){tone(360,.035,'square',.04)}else if(kind==='challenge'){tone(460,.08,'sine',.055);tone(690,.08,'sine',.04,.08)}else if(kind==='coin'){[760,920].forEach((f,i)=>tone(f,.055,'triangle',.055,i*.05))}else if(kind==='level'){[420,540,720,960,1200].forEach((f,i)=>tone(f,.08,'triangle',.07,i*.06))}}
['pointerdown','touchend','click'].forEach(ev=>document.addEventListener(ev,start,{once:true,passive:true}));
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&ctx){ctx.resume&&ctx.resume();syncMute();music()}});
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action||'',p=e.target.closest('[data-page]')?.dataset.page||'';if(a==='spin'||a==='auto')sfx('spin');else if(a==='topup'||a==='daily'||a.startsWith('pack'))sfx('coin');else if(a.startsWith('challenge')||p==='challenges')sfx('challenge');else if(a==='sound'){setTimeout(()=>{syncMute();if(enabled())flash('SOUND ON','Music and effects unlocked')},60)}else sfx('button')},true);
const obs=new MutationObserver(()=>{let wp=document.querySelector('#winPopup');if(wp&&wp.classList.contains('show')&&!wp._sound){wp._sound=1;sfx('win');setTimeout(()=>wp._sound=0,1500)}});obs.observe(document.documentElement,{subtree:true,attributes:true,attributeFilter:['class']});
setInterval(syncMute,1000);
window.SeaEagleAudio={start,sfx,syncMute};
})();