(()=>{
let ctx, master, musicGain, started=false, musicTimer=null, step=0;
const scale=[130.81,146.83,164.81,196.00,220.00,246.94,261.63,293.66];
function make(){ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();if(!master){master=ctx.createGain();master.gain.value=.36;master.connect(ctx.destination);musicGain=ctx.createGain();musicGain.gain.value=.045;musicGain.connect(master)}return ctx}
function tone(f=440,d=.08,type='square',vol=.08,delay=0){try{make();const now=ctx.currentTime+delay,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,now);g.gain.setValueAtTime(vol,now);g.gain.exponentialRampToValueAtTime(.0001,now+d);o.connect(g);g.connect(master);o.start(now);o.stop(now+d+.03)}catch(e){}}
function noise(d=.12,vol=.05){try{make();const len=Math.max(1,Math.floor(ctx.sampleRate*d)),buf=ctx.createBuffer(1,len,ctx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const s=ctx.createBufferSource(),g=ctx.createGain();g.gain.value=vol;s.buffer=buf;s.connect(g);g.connect(master);s.start()}catch(e){}}
function music(){if(musicTimer)return;musicTimer=setInterval(()=>{if(!ctx||ctx.state==='suspended')return;let bass=scale[step%scale.length]/2;let lead=scale[(step*2+3)%scale.length];tone(bass,.09,'triangle',.026,0);if(step%2===0)tone(lead,.06,'sine',.018,.03);if(step%4===0)noise(.025,.018);step++},360)}
function start(){try{make();ctx.resume&&ctx.resume();if(started)return;started=true;music();flash('SOUND ON','Music starts after first tap')}catch(e){}}
function flash(a,b){let t=document.querySelector('#toast');if(!t)return;t.innerHTML=a+'<small>'+b+'</small>';t.classList.add('show');clearTimeout(t._audioT);t._audioT=setTimeout(()=>t.classList.remove('show'),1200)}
function sfx(kind){if(!started)start();if(kind==='spin'){tone(180,.07,'sawtooth',.08);tone(240,.06,'sawtooth',.05,.07);noise(.08,.025)}else if(kind==='win'){[520,660,820,1040].forEach((f,i)=>tone(f,.09,'triangle',.075,i*.07));noise(.22,.035)}else if(kind==='button'){tone(360,.035,'square',.04)}else if(kind==='challenge'){tone(460,.08,'sine',.055);tone(690,.08,'sine',.04,.08)}else if(kind==='coin'){[760,920].forEach((f,i)=>tone(f,.055,'triangle',.055,i*.05))}}
document.addEventListener('pointerdown',start,{once:true,passive:true});
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action||'',p=e.target.closest('[data-page]')?.dataset.page||'';if(a==='spin'||a==='auto')sfx('spin');else if(a==='topup'||a==='daily'||a.startsWith('pack'))sfx('coin');else if(a.startsWith('challenge')||p==='challenges')sfx('challenge');else sfx('button')},true);
const obs=new MutationObserver(()=>{let wp=document.querySelector('#winPopup');if(wp&&wp.classList.contains('show')&&!wp._sound){wp._sound=1;sfx('win');setTimeout(()=>wp._sound=0,1600)}});obs.observe(document.documentElement,{subtree:true,attributes:true,attributeFilter:['class']});
window.SeaEagleAudio={start,sfx};
})();