(()=>{
let ctx, gain, started=false, loop=null, step=0;
const notes=[196,246.94,293.66,329.63,392,440,493.88,587.33];
function toast(a,b=''){let t=document.querySelector('#toast');if(!t)return;t.innerHTML=a+(b?'<small>'+b+'</small>':'');t.classList.add('show');clearTimeout(t._boostT);t._boostT=setTimeout(()=>t.classList.remove('show'),1400)}
function badge(msg){let b=document.querySelector('.audioBadge');if(!b){b=document.createElement('div');b.className='audioBadge';document.querySelector('#app')?.appendChild(b)}b.textContent=msg;b.classList.add('show');clearTimeout(b._t);b._t=setTimeout(()=>b.classList.remove('show'),1500)}
function make(){ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();if(!gain){gain=ctx.createGain();gain.gain.value=.42;gain.connect(ctx.destination)}return ctx}
function on(){try{return JSON.parse(localStorage.getItem('seaEagleSpinsV11')||'{}').sound!==false}catch(e){return true}}
function tone(f,d=.1,type='sine',vol=.18,delay=0){if(!on())return;try{make();ctx.resume&&ctx.resume();let now=ctx.currentTime+delay,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(vol,now);g.gain.exponentialRampToValueAtTime(.0001,now+d);o.connect(g);g.connect(gain);o.start(now);o.stop(now+d+.03)}catch(e){}}
function thump(){if(!on())return;try{make();ctx.resume&&ctx.resume();let len=Math.floor(ctx.sampleRate*.09),buf=ctx.createBuffer(1,len,ctx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);let s=ctx.createBufferSource(),g=ctx.createGain();g.gain.value=.07;s.buffer=buf;s.connect(g);g.connect(gain);s.start()}catch(e){}}
function start(show=true){try{make();ctx.resume&&ctx.resume();started=true;if(show){toast('SOUND UNLOCKED','iPhone audio ready');badge('SOUND ON')}if(!loop){loop=setInterval(()=>{if(!started||!on()||document.hidden)return;let n=notes[step%notes.length];tone(n/2,.08,'triangle',.045,0);if(step%2===0)tone(notes[(step+3)%notes.length],.055,'sine',.03,.025);if(step%4===0)thump();step++},420)}}catch(e){toast('SOUND BLOCKED','Tap again or check silent mode')}}
function fanfare(){start(false);[392,493.88,587.33,783.99,987.77].forEach((n,i)=>tone(n,.09,'triangle',.22,i*.07));thump();setTimeout(thump,120);badge('TEST SOUND')}
function inject(){let h=document.querySelector('#pageContent h1');if(!h||h.textContent.trim()!=='MORE')return;let list=document.querySelector('#pageContent .list');if(!list||list.querySelector('[data-action="testSound"]'))return;let btn=document.createElement('button');btn.className='tile';btn.dataset.action='testSound';btn.innerHTML='<div class="symbolTile bonus"><div class="symbolArt">🔊</div><div class="symbolName">SOUND</div></div><b>TEST SOUND</b><span>Tap to unlock and play a test fanfare</span>';list.insertBefore(btn,list.firstChild)}
['pointerdown','touchstart','click'].forEach(ev=>document.addEventListener(ev,()=>start(false),{once:true,passive:true}));
document.addEventListener('click',e=>{let a=e.target.closest('[data-action]')?.dataset.action||'';if(a==='testSound'){e.preventDefault();fanfare()}else if(a==='sound'){setTimeout(()=>{start(true);fanfare()},80)}else if(a==='spin'){start(false);tone(180,.08,'sawtooth',.2);tone(260,.07,'square',.13,.07);thump()}else if(a==='payouts'||a==='challengeManly'||a==='challengeCoffee'||a==='challengeCoco'||a==='challengeConcrete'||a==='challengeZach'||a==='challengeDavid'){start(false);tone(520,.08,'sine',.16);tone(780,.08,'sine',.12,.08)}},true);
const obs=new MutationObserver(()=>{inject();let w=document.querySelector('#winPopup');if(w&&w.classList.contains('show')&&!w._boost){w._boost=1;fanfare();setTimeout(()=>w._boost=0,1500)}});obs.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
window.SeaEagleSoundTest=fanfare;
})();